# Generated by Django 4.1.6 on 2023-02-12 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('score', models.IntegerField(max_length=3)),
                ('image', models.ImageField(upload_to='games/')),
            ],
            options={
                'db_table': 'products',
            },
        ),
    ]
